// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package querytest

import (
	"database/sql"
)

type Comment struct {
	ID         int32         `db:"id" json:"id"`
	PostID     sql.NullInt32 `db:"post_id" json:"post_id"`
	Content    string        `db:"content" json:"content"`
	AuthorName string        `db:"author_name" json:"author_name"`
}

type Post struct {
	ID      int32  `db:"id" json:"id"`
	UserID  int32  `db:"user_id" json:"user_id"`
	Title   string `db:"title" json:"title"`
	Content string `db:"content" json:"content"`
}

type Profile struct {
	ID        int32          `db:"id" json:"id"`
	UserID    sql.NullInt32  `db:"user_id" json:"user_id"`
	Bio       sql.NullString `db:"bio" json:"bio"`
	AvatarUrl sql.NullString `db:"avatar_url" json:"avatar_url"`
}

type User struct {
	ID    int32  `db:"id" json:"id"`
	Name  string `db:"name" json:"name"`
	Email string `db:"email" json:"email"`
}
