// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type Post struct {
	ID         int64
	Title      string
	Body       string
	AuthorID   sql.NullInt64
	ReviewerID sql.NullInt64
}
